# server
ACTIVE_PROFILE: prod
SERVER_PORT: 9093
#DATABASE
DATABASE_USERNAME: root
DATABASE_PASSWORD: root
DATABASE: event_managementDB_prod
DATABASE_HOST: localhost
DATABASE_PORT: 5432
JDBC_CONNECTION: jdbc:postgresql
#DATABASE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
DDL_AUTO: update
DRIVER_CLASS_NAME: org.postgresql.Driver
#  sql:
#   init:
#   mode: always
#   continue-on-error: false
#   schema-locations: schema.sql   #classpath:/schema.sql
#   data-locations: data.sql   #classpath:/data.sql

MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: your_email@gmail.com

















spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/event_managementDB_prod
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false




















