###configuration########
server:
  port: 9093
  servlet:
    context-path: /api.event_management/v1

spring:
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/event_managementDB_prod
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false




















