# server
ACTIVE_PROFILE: test
SERVER_PORT: 9095
spring:
  datasource:
    url: jdbc:h2:mem:event_managementDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: your_email@gmail.com









