###configuration########
server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api.event_management/v1  #swagger-path:/api.event_management/v1/swagger-ui/index.html#/
  error:
    path: /error
    whitelabel:
      enabled: false

spring:
  application:
    name: Event_Management-App

  profiles:
    active: ${ACTIVE_PROFILE:dev}  # test prod dev

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 10MB

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${JDBC_CONNECTION}://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}
    driver-class-name: ${DRIVER_CLASS_NAME}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        globally_quoted_identifiers: true
        #dialect: ${DATABASE_DIALECT}
        format_sql: true

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: event_management_schema_history

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 10000
          timeout: 10000
          starttls:
            enable: true
            required: false
            auth: true
      verify:
        host: ${VERIFY_EMAIL_HOST}

  security:
    oauth2:
      resource server:
        jwt:
          public-key-location: public.pem
          private-key-location: chave.key










